Repository uninus-opensource/uninus-pkm, pull requests merged in 2024-03, with the labels that each got.

#5 feat: initial tRPC
  apps/web/backoffice/app/api/auth/[...nextauth]/route.ts
  apps/web/backoffice/tsconfig.json
  apps/web/market/app/_modules/index.tsx
  apps/web/market/app/api/auth/[...nextauth]/route.ts
  apps/web/market/app/api/trpc/[trpc]/route.ts
  apps/web/market/app/global.css
  apps/web/market/app/layout.tsx
  apps/web/market/app/page.module.css
  apps/web/market/app/page.tsx
  apps/web/market/specs/index.spec.tsx
  apps/web/market/tsconfig.json
  apps/web/tourism/app/api/auth/[...nextauth]/route.ts
  libs/web/service/src/index.ts
  libs/web/service/src/server.ts
  libs/web/service/src/trpc/config.ts
  libs/web/service/src/trpc/index.ts
  libs/web/service/src/trpc/market/client/client.ts
  libs/web/service/src/trpc/market/client/index.ts
  libs/web/service/src/trpc/market/client/provider.tsx
  libs/web/service/src/trpc/market/index.ts
  libs/web/service/src/trpc/market/server/index.ts
  tsconfig.base.json
Labels: enhancement, help wanted

#6 feature: added landing page for tourism web
  apps/web/tourism/app/(landing-page)/_module/index.tsx
  apps/web/tourism/app/(landing-page)/page.tsx
  apps/web/tourism/app/global.css
  apps/web/tourism/app/page.tsx
  apps/web/tourism/public/assets/bandung.jpg
  apps/web/tourism/public/assets/image-placeholder.png
  apps/web/tourism/public/assets/logo.svg
  apps/web/tourism/specs/index.spec.tsx
  apps/web/tourism/tailwind.config.js
  libs/web/components/molecules/src/index.ts
  libs/web/components/molecules/src/navbar/navbar.tsx
  libs/web/components/molecules/src/tourism/footer/footer.tsx
  libs/web/components/molecules/src/tourism/footer/index.ts
  libs/web/components/molecules/src/tourism/navbar/index.ts
  libs/web/components/molecules/src/tourism/navbar/navbar.tsx
  package-lock.json
  package.json
Labels: enhancement

#16 chore: adjust button as like design guidelines (tentative)
  apps/web/backoffice/app/(auth)/auth/(nested)/register/_modules/personal/index.tsx
  apps/web/backoffice/app/(auth)/auth/login/_modules/index.tsx
  apps/web/backoffice/app/(protected)/dashboard/(activity)/activity/_modules/index.tsx
  apps/web/backoffice/app/(protected)/dashboard/(submission)/submission/_modules/index.tsx
  apps/web/backoffice/tsconfig.storybook.json
  design-token.js
  libs/entities/src/types/common/index.ts
  libs/web/components/atoms/src/button/button.tsx
  libs/web/components/organisms/src/datatable/datatable.tsx
Labels: enhancement, FE

#19 chore: adjust Inputs to matched the design guidelines (tentative)
  apps/web/tourism/app/(landing-page)/_module/index.tsx
  libs/entities/src/types/common/index.ts
  libs/entities/src/types/common/style.ts
  libs/web/components/atoms/src/inputs/checkbox/checkbox.tsx
  libs/web/components/atoms/src/inputs/select/select.tsx
  libs/web/components/atoms/src/inputs/text/text.tsx
  libs/web/components/atoms/src/message/message.tsx
  libs/web/components/molecules/src/tourism/navbar/navbar.tsx
  libs/web/components/templates/src/fieldset/fieldset.tsx
Labels: enhancement, FE, Tourism

#20 refactor : change color style on input
  libs/entities/src/types/common/style.ts
  libs/web/components/atoms/src/inputs/text/text.tsx
  libs/web/components/atoms/src/message/message.tsx
Labels: enhancement, FE

#22 Feat/tourism login page : Slicing login page for dashboard tourism
  apps/web/tourism/app/(auth)/auth/login/_modules/index.tsx
  apps/web/tourism/app/(auth)/auth/login/_modules/login.spec.tsx
  apps/web/tourism/app/(auth)/auth/login/loading.tsx
  apps/web/tourism/app/(auth)/auth/login/page.tsx
  apps/web/tourism/app/(auth)/template.tsx
  apps/web/tourism/public/assets/logo-desa.png
  libs/web/components/atoms/src/button/button.tsx
  libs/web/components/templates/src/form/form.tsx
Labels: enhancement, FE, Tourism
